services:
  linktamer-api:
    build:
      context: linktamer-back
      dockerfile: src/LinkTamer.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: linktamer-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  linktamer-frontend:
    build:
      context: linktamer-front
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:8080"
    container_name: linktamer-front
    ports:
      - "80:80"
    volumes:
      - ./linktamer-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - linktamer-api

  redis:
    image: redis:7-alpine
    container_name: linktamer-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
